name: finance_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Email sending
  mailer: ^6.0.0

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  pinput: ^6.0.2
  shimmer: ^3.0.0
  
  # Database & Storage
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  
  # State Management & Routing
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.1.0
  
  # Charts
  fl_chart: ^1.1.1
  
  # Camera & Image
  camera: ^0.11.4
  image_picker: ^1.0.5
  mobile_scanner: ^7.2.0
  
  # Networking & APIs
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  
  # Utilities
  intl: ^0.20.2
  csv: ^7.1.0
  logger: ^2.6.2
  crypto: ^3.0.3
  
  # JSON & Code Generation
  json_annotation: ^4.11.0
  freezed_annotation: ^3.1.0
  
  # Sharing
  share_plus: ^12.0.1
  
  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  
  # OTP
  email_otp: ^3.1.0
  riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env